openapi: 3.0.1
info:
  title: FRIDA Car Claims Data Schema
  description: 'Die FRIDA Schaden API - ermöglicht es Nutzer:innen im Schadenfall die wichtigsten Versicherungs- und Unfalldaten über eine Schadenplattform direkt an den Versicherer zu übertragen und den Schaden damit offiziel zu melden.'
  termsOfService: 'https://github.com/FRIDA-official'
  contact:
    name: Florian Neuß
    email: floneuss99@gmail.com
    url: 'https://github.com/FRIDA-api/FRIDA-car'
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
  version: 0.0.1
servers:
  - url: 'https://stoplight.io/mocks/claimstobe/claims-data-schema/676129330'
    description: Mock API
  - url: 'https://test-api-impl-backend-jaxrs.herokuapp.com/v2'
    description: Staging
  - url: 'https://test-api-impl-backend-jaxrs.xyz.com/v2'
    description: Production
tags:
  - name: Claims
    description: Claims
externalDocs:
  description: Externe API Dokumentation
  url: 'https://github.com/FRIDA-api/frida-car-dokumentation'
paths:
  '/claimsdata/{policyNumber}':
    parameters:
      - $ref: '#/components/parameters/policyNumber'
    get:
      operationId: getClaimByPID
      summary: Get Claim by PID
      description: Get Claim by PID
      tags:
        - Claims
      parameters:
        - $ref: '#/components/parameters/policyNumber'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Claimsdata'
    put:
      operationId: updateClaimByPID
      summary: Update Claim by PID
      description: Update Claim by PID
      tags:
        - Claims
      parameters:
        - $ref: '#/components/parameters/policyNumber'
      requestBody:
        $ref: '#/components/requestBodies/Claimdata'
      responses:
        '200':
          description: Fetched a Claim-Data-Set by PolicyNumber
          $ref: '#/components/responses/Claimdata'
    post:
      operationId: createClaimByPID
      summary: Create Claim by PID
      description: Create Claim by PID
      tags:
        - Claims
      parameters:
        - $ref: '#/components/parameters/policyNumber'
      requestBody:
        $ref: '#/components/requestBodies/Claimdata'
      responses:
        '201':
          $ref: '#/components/responses/Claimdata'
        '403':
          description: Authorization error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorList'
        '500':
          description: Generic Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorList'
components:
  schemas:
    Claimsdata:
      description: Holds all information required for submitting a `Comprehensive Claim` to the insurance company. All fields are flat (no nested objects).
      type: object
      properties:
        language:
          type: string
          description: Sprache
          example: DE
          enum:
            - DE
            - EN
            - FR
            - ES
            - IT
            - NL
            - PL
        accidentDate:
          type: string
          description: Unfalldatum ohne Zeit
          format: date
          example: '2019-08-24'
        accidentTime:
          type: string
          description: Unfall Zeit
          format: time
          example: '08:30:00'
        accidentPostalCode:
          type: string
          description: PLZ des Unfallorts
          example: '50181'
        accidentCity:
          type: string
          description: Ort des Unfalls
          example: Bedburg
        accidentStreetName:
          type: string
          description: Straße des Unfallorts
          example: Germaniastraße
        accidentHouseNumber:
          type: string
          description: Hausnummer des Unfallorts
          example: 1b
        accidentDetails:
          type: string
          description: Unfallbeschreibung
        accidentReportNumber:
          type: string
          description: Unfallnummer der Polizei
          example: 2024-ABC123
        miscellaneousDamages:
          type: string
          description: weitere Sachschäden ja/nein
          enum:
            - not_specified
            - 'false'
            - 'true'
        miscellaneousDamageDescription:
          type: string
          description: Beschreibung der Sachschäden
          example: Frontstoßstangenschaden
        hasInjured:
          type: string
          description: Verletzte Person ja/nein
          enum:
            - not_specified
            - 'false'
            - 'true'
        injuredCount:
          type: string
          description: Anzahl verletzte Personen
        hasWitnesses:
          type: string
          description: Zeuge ja/nein
          enum:
            - not_specified
            - 'false'
            - 'true'
        witnessesCount:
          type: string
          description: Anzahl Zeugen
        witnesses:
          type: array
          description: Liste der Zeugen
          items:
            $ref: '#/components/schemas/WitnessDetails'
        insuranceHolderSalutation:
          type: string
          description: Anrede Versicherungsnehmer A
          enum:
            - Herr
            - Frau
        insuranceHolderTitle:
          type: string
          description: Titel Versicherungsnehmer A
          enum:
            - Dr.
            - Dr. Dr.
            - Prof.
        insuranceHolderName:
          type: string
          description: Vorname Versicherungsnehmer A
          example: Alice
        insuranceHolderSurName:
          type: string
          description: Nachname Versicherungsnehmer A
          example: Johnson
        insuranceHolderStreetName:
          type: string
          description: Straße Versicherungsnehmer A
          example: Germaniastraße
        insuranceHolderHouseNumber:
          type: string
          description: Hausnummer Versicherungsnehmer A
          example: 1b
        insuranceHolderPostalCode:
          type: string
          description: PLZ Versicherungsnehmer A
          example: '50181'
        insuranceHolderCity:
          type: string
          description: Ort Versicherungsnehmer A
          example: Bedburg
        insuranceHolderTelephone:
          type: string
          description: Telefonnummer Versicherungsnehmer A
          example: '+49(40)321070'
        insuranceHolderEmail:
          type: string
          description: E-Mail Versicherungsnehmer A
          example: example@gmail.com
        vatDeduction:
          type: string
          description: Vorsteuerabzug ja/nein (A)
          enum:
            - not_specified
            - 'false'
            - 'true'
        carBrand:
          type: string
          description: Fahrzeugmarke A
          example: BMW
        carModel:
          type: string
          description: Fahrzeugmodell A
          example: M5
        licensePlate:
          type: string
          description: Kennzeichen A
          example: BM LD1234
        insuranceCompany:
          type: string
          description: Versicherungsanbieter A
          example: HDI
        insuranceNumber:
          type: string
          description: Policennummer A
          example: V-123-345-678-5
        chassisNumber:
          type: string
          description: Fahrzeug-Identifizierungsnummer A
          example: W0L000051T2123456
        odometerReading:
          type: string
          description: aktueller Kilometerstand A
          example: '1200'
        greenCardNumber:
          type: string
          description: Grüne-Karte Nummer A
        validDateGreenCard:
          type: string
          description: Ablaufdatum der Grünen Karte A
          format: date
        allRiskInsurance:
          type: string
          description: Vollkaskoversichert ja/nein (A)
          enum:
            - not_specified
            - 'false'
            - 'true'
        otherInsuranceHolderSalutation:
          type: string
          description: Anrede Versicherungsnehmer B
          enum:
            - Herr
            - Frau
        otherInsuranceHolderTitle:
          type: string
          description: Titel Versicherungsnehmer B
          enum:
            - Dr.
            - Dr. Dr.
            - Prof.
        otherInsuranceHolderName:
          type: string
          description: Vorname Versicherungsnehmer B
          example: Bob
        otherInsuranceHolderSurName:
          type: string
          description: Nachname Versicherungsnehmer B
          example: Smith
        otherInsuranceHolderStreetName:
          type: string
          description: Straße Versicherungsnehmer B
        otherInsuranceHolderHouseNumber:
          type: string
          description: Hausnummer Versicherungsnehmer B
        otherInsuranceHolderPostalCode:
          type: string
          description: PLZ Versicherungsnehmer B
        otherInsuranceHolderCity:
          type: string
          description: Ort Versicherungsnehmer B
        otherInsuranceHolderTelephone:
          type: string
          description: Telefonnummer Versicherungsnehmer B
        otherInsuranceHolderEmail:
          type: string
          description: E-Mail Versicherungsnehmer B
        otherVatDeduction:
          type: string
          description: Vorsteuerabzug ja/nein (B)
          enum:
            - not_specified
            - 'false'
            - 'true'
        otherCarBrand:
          type: string
          description: Fahrzeugmarke B
        otherCarModel:
          type: string
          description: Fahrzeugmodell B
        otherLicensePlate:
          type: string
          description: Kennzeichen B
        otherInsuranceCompany:
          type: string
          description: Versicherungsanbieter B
        otherInsuranceNumber:
          type: string
          description: Policennummer B
        otherChassisNumber:
          type: string
          description: Fahrzeug-Identifizierungsnummer B
        otherOdometerReading:
          type: string
          description: aktueller Kilometerstand B
        otherGreenCardNumber:
          type: string
          description: Grüne-Karte Nummer B
        otherValidDateGreenCard:
          type: string
          description: Ablaufdatum der Grünen Karte B
          format: date
        otherAllRiskInsurance:
          type: string
          description: Vollkaskoversichert ja/nein (B)
          enum:
            - not_specified
            - 'false'
            - 'true'
        driverSalutation:
          type: string
          description: Anrede Fahrer A
          enum:
            - Herr
            - Frau
        driverName:
          type: string
          description: Vorname Fahrer A
        driverSurName:
          type: string
          description: Nachname Fahrer A
        driverStreetName:
          type: string
          description: Straße Fahrer A
        driverHouseNumber:
          type: string
          description: Hausnummer Fahrer A
        driverPostalCode:
          type: string
          description: PLZ Fahrer A
        driverCity:
          type: string
          description: Ort Fahrer A
        driverTelephone:
          type: string
          description: Telefonnummer Fahrer A
        driverEmail:
          type: string
          description: E-Mail Fahrer A
        driverDriverLicense:
          type: string
          description: Führerscheinnummer Fahrer A
          example: DR123456
        driverLicenseIssuingAuthority:
          type: string
          description: Führerschein ausgestellt von (A)
        driverDamagedParts:
          type: array
          description: Auswahl der beschädigten Stellen (A)
          items:
            type: string
            enum:
              - Motorhaube
              - Dach
              - Kofferraum/Heckklappe
              - Kühlergrill
              - Linke Fahrzeugseite
              - Rechte Fahrzeugseite
              - Vorderer Stoßfänger
              - Hinterer Stoßfänger
              - Fahrertür (vorne links)
              - Beifahrertür (vorne rechts)
              - Hintere linke Tür
              - Hintere rechte Tür
              - Vorderrad links
              - Vorderrad rechts
              - Hinterrad links
              - Hinterrad rechts
              - Windschutzscheibe
              - Heckscheibe
              - Seitenscheibe (vorne links)
              - Seitenscheibe (vorne rechts)
              - Seitenscheibe (hinten links)
              - Seitenscheibe (hinten rechts)
              - Linker Außenspiegel
              - Rechter Außenspiegel
              - Frontscheinwerfer links
              - Frontscheinwerfer rechts
              - Heckscheinwerfer links
              - Heckscheinwerfer rechts
              - Griffschalen (vorne links)
              - Griffschalen (vorne rechts)
              - Griffschalen (hinten links)
              - Griffschalen (hinten rechts)
              - Schweller links
              - Schweller rechts
              - Kotflügel links
              - Kotflügel rechts
            example: Motorhaube
        damageDescription:
          type: string
          description: Beschreibung sichtbare Schäden (A)
        additionalComments:
          type: string
          description: Bemerkungen des Fahrers (A)
        vehicleOperational:
          type: string
          description: Fahrbereitschaft des Fahrzeugs ja/nein (A)
          enum:
            - not_specified
            - 'true'
            - 'false'
        damageType:
          type: string
          description: Auswahl der Schadenursache (A)
          enum:
            - Auffahren
            - Rangieren/ Parken
            - Missachtung der Vorfahrt
            - Abbiegen
            - Abkommen von der Fahrbahn
            - Überholvorgang
            - Spurwechsel
            - Sonstiges
          example: Auffahren
        otherDriverSalutation:
          type: string
          description: Anrede Fahrer B
          enum:
            - Herr
            - Frau
        otherDriverName:
          type: string
          description: Vorname Fahrer B
        otherDriverSurName:
          type: string
          description: Nachname Fahrer B
        otherDriverStreetName:
          type: string
          description: Straße Fahrer B
        otherDriverHouseNumber:
          type: string
          description: Hausnummer Fahrer B
        otherDriverPostalCode:
          type: string
          description: PLZ Fahrer B
        otherDriverCity:
          type: string
          description: Ort Fahrer B
        otherDriverTelephone:
          type: string
          description: Telefonnummer Fahrer B
        otherDriverEmail:
          type: string
          description: E-Mail Fahrer B
        otherDriverDriverLicense:
          type: string
          description: Führerscheinnummer Fahrer B
        otherDriverLicenseIssuingAuthority:
          type: string
          description: Führerschein ausgestellt von (B)
        otherDriverDamagedParts:
          type: array
          description: Auswahl der beschädigten Stellen (B)
          items:
            type: string
            enum:
              - Motorhaube
              - Dach
              - Kofferraum/Heckklappe
              - Kühlergrill
              - Linke Fahrzeugseite
              - Rechte Fahrzeugseite
              - Vorderer Stoßfänger
              - Hinterer Stoßfänger
              - Fahrertür (vorne links)
              - Beifahrertür (vorne rechts)
              - Hintere linke Tür
              - Hintere rechte Tür
              - Vorderrad links
              - Vorderrad rechts
              - Hinterrad links
              - Hinterrad rechts
              - Windschutzscheibe
              - Heckscheibe
              - Seitenscheibe (vorne links)
              - Seitenscheibe (vorne rechts)
              - Seitenscheibe (hinten links)
              - Seitenscheibe (hinten rechts)
              - Linker Außenspiegel
              - Rechter Außenspiegel
              - Frontscheinwerfer links
              - Frontscheinwerfer rechts
              - Heckscheinwerfer links
              - Heckscheinwerfer rechts
              - Griffschalen (vorne links)
              - Griffschalen (vorne rechts)
              - Griffschalen (hinten links)
              - Griffschalen (hinten rechts)
              - Schweller links
              - Schweller rechts
              - Kotflügel links
              - Kotflügel rechts
            example: Motorhaube
        otherDamageDescription:
          type: string
          description: Beschreibung sichtbare Schäden (B)
        otherAdditionalComments:
          type: string
          description: Bemerkungen des Fahrers (B)
        otherVehicleOperational:
          type: string
          description: Fahrbereitschaft des Fahrzeugs ja/nein (B)
          enum:
            - not_specified
            - 'true'
            - 'false'
        otherDamageType:
          type: string
          description: Auswahl der Schadenursache (B)
          enum:
            - Auffahren
            - Rangieren/ Parken
            - Missachtung der Vorfahrt
            - Abbiegen
            - Abkommen von der Fahrbahn
            - Überholvorgang
            - Spurwechsel
            - Sonstiges
          example: Auffahren
      additionalProperties: false
    WitnessDetails:
      description: Holds all information of a single witness.
      type: object
      properties:
        salutation:
          type: string
          description: Anrede Zeuge
          enum:
            - Herr
            - Frau
        name:
          type: string
          description: Vorname Zeuge
        surName:
          type: string
          description: Nachname Zeuge
        streetName:
          type: string
          description: Straße Zeuge
        houseNumber:
          type: string
          description: Hausnummer Zeuge
        postalCode:
          type: string
          description: PLZ Zeuge
        city:
          type: string
          description: Ort Zeuge
        telephone:
          type: string
          description: Telefonnummer Zeuge
        email:
          type: string
          description: E-Mail Zeuge
      additionalProperties: false
    ErrorList:
      description: Error object
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            required:
              - code
              - title
              - detail
            properties:
              code:
                type: string
                description: The code of the error
              title:
                type: string
                description: A displayable title of the error type
              detail:
                type: string
                description: Detail of the error
              meta:
                type: object
                description: Optional additional data for specific error types
            additionalProperties: false
      required:
        - errors
      additionalProperties: false
  requestBodies:
    Claimdata:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Claimsdata'
  responses:
    Claimdata:
      description: Creates a new Claims-Data-Set
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Claimsdata'
  parameters:
    policyNumber:
      name: policyNumber
      in: path
      description: Policy Number Headline
      required: true
      style: simple
      explode: false
      schema:
        type: string
